version: "3"

services:

  database:
    container_name: omerodb
    image: "postgres:11"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
#    volumes:
#      - "database:/var/lib/postgresql/data"

  omeroserver:
    # This container uses the tag for the latest server release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    container_name: omeroserver
    image: "openmicroscopy/omero-server:5"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero

      CONFIG_omero_client_icetransports: ssl,wss

      # Self-signed certificates are needed if you want to use secure
      # websocket proxying between nginx and omero (Nginx can't use ADH).
      # If you are connecting directly to OMERO.server wss this isn't
      # needed since the clients are configured to use ADH.
      CONFIG_omero_glacier2_IceSSL_Ciphers: ADH:HIGH
      CONFIG_omero_glacier2_IceSSL_DefaultDir: /etc/ssl/selfsigned
      CONFIG_omero_glacier2_IceSSL_CAs: cacert.pem
      CONFIG_omero_glacier2_IceSSL_CertFile: server.p12
      CONFIG_omero_glacier2_IceSSL_Password: secret
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - ./init:/opt/omero/init
      - "./certs:/etc/ssl/selfsigned:ro${VOLOPTS-}"
    command: sh -c "chmod +x /opt/omero/init/populate.sh && sh /opt/omero/init/populate.sh"
#      - "omero:/OMERO"

  omeroweb:
    # This container uses the tag for the latest web release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    #image: "openmicroscopy/omero-web-standalone:5"
    container_name: omeroweb
    build: omero-web
    volumes:
      - ./config/50-omero-web-app-config.omero:/opt/omero/web/config/50-omero-web-app-config.omero
    environment:
      OMEROHOST: omeroserver
    networks:
      - omero
    ports:
      - "4080:4080"

  nginx:
    image: library/nginx:1.14
    networks:
      - omero
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro${VOLOPTS-}"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro${VOLOPTS-}"
      - "./certs:/etc/nginx/ssl:ro${VOLOPTS-}"

networks:
  omero:

#volumes:
#  database:
#  omero: